CREATE TABLE RODADA_VARIACAO
(
  id bigint NOT NULL,
  variacao integer NOT NULL,
  rodada_id bigint NOT NULL,
  ramo_id bigint NOT NULL,
  CONSTRAINT fk_rodada_variacao_rodada FOREIGN KEY (rodada_id)
      REFERENCES RODADA (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_rodada_variacao_ramo_atividade FOREIGN KEY (ramo_id)
      REFERENCES RAMO_ATIVIDADE (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

ALTER TABLE RODADA_VARIACAO 
ADD CONSTRAINT rodada_variacao_pkey PRIMARY KEY (id)
;

CREATE SEQUENCE RODADA_VARIACAO_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 43
  CACHE 1;